### ISSUE TITLE
Please improve response time.

### ISSUE THREAD

**Issue by m-negahi** [ray-di/Ray.RayDiForLaravel#3]
I have installed a Laravel telescope to track request times, and in my case, a simple controller returns a view and using a logger logs it to the storage directory.

When I send a request to the home page without Aop the response time is around 538ms, But when I send a request to a home with enabled Aop the request time is 1215ms.

`Loggable Attribute: `

```php 
<?php

declare(strict_types=1);

namespace App\Attribute;

use Attribute;
use Ray\Di\Di\Qualifier;

#[Attribute, Qualifier]
final class Loggable
{
}
```

`LoggerInterceptor: `

```php 
<?php

declare(strict_types=1);

namespace App\Interceptor;
use Ray\Aop\MethodInterceptor;
use Ray\Aop\MethodInvocation;
use function microtime;

final class LoggerInterceptor implements MethodInterceptor
{
    public function invoke(MethodInvocation $invocation)
    {
        \Illuminate\Support\Facades\Log::info('Welcome view proccessed.');
    }
}
```

`Controller:`

```php
<?php

namespace App\Http\Controllers;

use App\Attribute\Loggable;
use App\Domain\Double\DoubleInterface;
use Ray\Di\Di\Inject;
use Ray\Di\Di\PostConstruct;
use Ray\Di\Di\Set;
use Ray\Di\ProviderInterface;

class HelloController extends Controller
{
    #[Loggable]
    public function index()
    {
        return view('welcome');
    }
}
```

**Comment by koriym** [comment]
We are currently looking into implementing performance tuning for production. Once implemented, response time should improve. Stay tuned.

**Comment by koriym** [comment]
If you only want to measure the impact of AOP, you should do without the LoggerInterceptor implementation.

```php
    public function invoke(MethodInvocation $invocation)
    {
        // do nothing
    }
```

**Comment by koriym** [comment]
@kindslayer We have made our first release. I think this solves the performance problem. Thanks for your interest and the patiance!
